# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/AudioProcessing/Project/Repo/SimpleMixer/SW/Vivado/Vivado_SimpleMixer/Vivado_SimpleMixer.srcs/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
# IP: The module: 'design_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AudioProcessing/Project/Repo/SimpleMixer/SW/Vivado/Vivado_SimpleMixer/Vivado_SimpleMixer.gen/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/AudioProcessing/Project/Repo/SimpleMixer/SW/Vivado/Vivado_SimpleMixer/Vivado_SimpleMixer.srcs/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
# IP: The module: 'design_1_xbar_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AudioProcessing/Project/Repo/SimpleMixer/SW/Vivado/Vivado_SimpleMixer/Vivado_SimpleMixer.gen/sources_1/bd/design_1/ip/design_1_xbar_5/design_1_xbar_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
